version: "2.1"

volumes:
  mariadb-data:

services:
  
  alpine-nginx-php-container:
    build:
      context: ./
      dockerfile: ./nginx-php.Dockerfile
    container_name: alpine-nginx-php-container
    ports:
      - "80:80"
      - "443:443"
    environment:
      TZ: "Europe/London"
      PHP_ERRORS: 1
      PHP_POST_MAX_SIZE: 250
      PHP_UPLOAD_MAX_FILESIZE: 250
    # remove the volume when using pi
    #volumes:
    #  - .:/var/www/html

  wpe:
    restart: always
    build:
      context: ./
      dockerfile: ./Dockerfile.wpe
    privileged: true
    ports:
      - "8080:8080"
    command: bash -c "echo 'sleeping for 60' && sleep 60 && /wpe-init"
    depends_on:
      - alpine-nginx-php-container

  honestyfood-mariadb:
    build:
      context: ./
      dockerfile: ./Dockerfile.mariadb
    container_name: honestyfood-mariadb
    working_dir: /application
    volumes:
      - mariadb-data:/config/databases
    #  - ./mariadb-data:/config/databases
    #command: bash -c "echo 'sleeping' && sleep 30 && echo 'creating' && /usr/bin/mysql -proot -e 'CREATE DATABASE IF NOT EXISTS honestyfood character set UTF8mb4 collate utf8mb4_bin;' && echo 'importing' && /usr/bin/mysql -proot honestyfood < /application/create-tables.sql"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=honestyfood
      - MYSQL_USER=oli
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_HOST=%
    ports:
      - "7074:3306"
