FROM petrosagg/balena-wpe:raspberrypi3-094d55a

COPY balena-wpe/udev-rules /etc/udev/rules.d/

COPY balena-wpe/wpe-init /wpe-init
RUN chmod +x /wpe-init

ENV TOHORA_VERSION=0.3.2
RUN wget -O tohora.tgz \
    "https://github.com/mozz100/tohora/releases/download/v"$TOHORA_VERSION"/tohora_"$TOHORA_VERSION"_Linux_armv5.tar.gz" \
    && tar xzf tohora.tgz \
    && rm tohora.tgz

COPY public /var/lib/public_html

ENV WPE_URL="http://alpine-nginx-php-container"
ENV WPE_BCMRPI_CURSOR=1
